version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 